- project:
    templates:
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - check-requirements
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-py36:
            voting: false
        - horizon-openstack-tox-python3-django111
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
    gate:
      jobs:
        - horizon-openstack-tox-python3-django111
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon

