- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs-horizon
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py36:
            voting: false
            required-projects:
              - openstack/horizon
        - horizon-openstack-tox-python3-django111
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
    gate:
      jobs:
        - horizon-openstack-tox-python3-django111
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon

